# Defines the containers (services) and their structure 

version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_pass
      POSTGRES_DB: fastapi_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed host port from 5432 to 5433

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://fastapi_user:fastapi_pass@db:5432/fastapi_db
      # Keep container's internal port 5432 in URL because 'db' service is on Docker network

volumes:
  postgres_data:

